server:
  port: 999
spring:
  datasource:
    url: jdbc:mysql://184.170.211.6:3306/sss?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true
    username: sss
    password: 123456qq
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
   com.zsgc: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
