server:
  port: 888
spring:
  datasource:
    url: jdbc:mysql://103.45.101.235:3306/sss?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true
    username: sss
    password: 123456qq
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 103.45.103.31
    password: 1234
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  thymeleaf:
    cache: false



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
   com.zsgc: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
